# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180604_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(blank=True, upload_to='post_images/'),
        ),
    ]
