# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180716_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participators',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
