# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.TimeField(default='01:00:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_from',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_to',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
