# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportfollower',
            old_name='sport',
            new_name='sport_id',
        ),
    ]
