# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportfollower',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='sportfollower',
            name='sport',
        ),
        migrations.DeleteModel(
            name='SportFollower',
        ),
    ]
