# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportfollower',
            name='sport_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
