# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20180701_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportfollower',
            old_name='sport_id',
            new_name='sport',
        ),
    ]
