# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_sportfollower_sport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportfollower',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport', unique=True),
        ),
        migrations.AlterField(
            model_name='sportfollower',
            name='sport_name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
