# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0002_auto_20180701_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(blank=True, max_length=20)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport')),
            ],
        ),
    ]
