# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20180702_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sport_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
