# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20180701_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportfollower',
            name='sport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport'),
        ),
        migrations.AlterField(
            model_name='sportfollower',
            name='sport_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
