# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_auto_20180703_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='sport_image',
            field=models.ImageField(blank=True, upload_to='sport_picture/'),
        ),
    ]
