# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='Medha', max_length=200),
        ),
    ]
