# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 14:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='POINT(78.9629 20.5937)', geography=True, max_length=40, srid=4326),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='Male', max_length=1),
        ),
    ]
