# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0002_profile_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
