# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0004_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to='profile_picture/'),
        ),
    ]
