# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
